{
 "title": "VMware performance",
 "description": "A nice per-VM(or per multiple VM) overview of VMware performance metrics.",
 "tags": [ "vmware" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "type", "query": "show measurements" },
   {
    "name": "host",
    "query": "show tag values with key = \"host\" "
   },
   {
    "name": "name",
    "query": "show tag values from /$type/ with key = \"name\" where host =~ /$host/"
   },
   {
    "name": "datastore",
    "query": "SHOW TAG VALUES WITH KEY =\"datastore\" WHERE \"name\" =~ /$name/  and \"host\" =~ /$host/"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "usage $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"cpu_usage_average\")  / 100 FROM \"virtualmachine\" WHERE \"name\" =~ /^$name$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Ready %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu ready $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"cpu_ready_summation\")  / 6000000) FROM $type WHERE \"name\" =~ /$name$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "mem used $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "mem_consumed_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/$name$/" }
     ]
    },
    {
     "alias": "mem provisioned $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$type$/",
     "select": [
      [
       {
        "params": [
         "mem_capacity_provisioned_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Read/Write average operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "read $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT mean(\"datastore_numberreadaveraged_average\") FROM \"vsphere\" WHERE \"name\" =~ /$name$/ AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       {
        "params": [
         "datastore_numberreadaveraged_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "write $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT mean(\"datastore_numberwriteaveraged_average\") FROM \"vsphere\" WHERE \"name\" =~ /$name$/ AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       {
        "params": [
         "datastore_numberwriteaveraged_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Read/Write in kBps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "read $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT mean(\"datastore_read_average\")  * 1000 FROM \"vsphere\" WHERE \"name\" =~ /$name$/ AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "datastore_read_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "write $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT mean(\"datastore_write_average\")  * 1000 FROM \"vsphere\" WHERE \"name\" =~ /$name$/ AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "datastore_write_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "read latency $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT mean(\"datastore_totalreadlatency_average\") FROM /$type$/ WHERE \"name\" =~ /$name$/ AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       {
        "params": [
         "datastore_totalreadlatency_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "write latency $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT mean(\"datastore_totalwritelatency_average\") FROM \"vsphere\" WHERE \"name\" =~ /$name$/ AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       {
        "params": [
         "datastore_totalwritelatency_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Other machines on the same datastore",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT mean(\"datastore_numberwriteaveraged_average\") + mean(\"datastore_numberreadaveraged_average\") as \"IOPS avg\", max(\"datastore_numberwriteaveraged_average\") + max(\"datastore_numberreadaveraged_average\") as \"IOPS max\", mean(\"datastore_totalreadlatency_average\") + mean(\"datastore_totalwritelatency_average\") as \"latency avg\", max(\"datastore_totalreadlatency_average\") + max(\"datastore_totalwritelatency_average\") as \"latency max\"   FROM \"virtualmachine\" WHERE \"datastore\" =~ /^$datastore$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY  \"name\", \"datastore\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datastore", "operator": "=~", "value": "/^$datastore$/" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Network Kbps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "received $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/$name$/" }
     ]
    },
    {
     "alias": "transmitted $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Packages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "received $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "net_packetsrx_summation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "transmitted $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "net_packetstx_summation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  }
 ]
}