{
 "title": "Home",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "switches",
    "label": "Switches",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /switch/ "
   },
   {
    "name": "SprinklerZones",
    "label": "Sprinkler Zones",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /switch/ "
   }
  ]
 },
 "panels": [
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Outside Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weather.my_ecobee",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Wind Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weather.my_ecobee",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Average Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate.my_ecobee",
     "select": [
      [
       { "params": [ "current_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Living Room",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "living_room_temperature" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "bedroom_temperature" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Office",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "home_office_temperature" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Basement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "basement_temperature" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Garage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "garage_temperature" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Ecobee Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate.my_ecobee",
     "select": [
      [
       { "params": [ "current_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Basement Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "basement_humidity" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Garage Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "garage_humidity" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Weather",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weather.my_ecobee",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Office Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "tasmotawork_energy_power" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aquarium Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "tasmotaav_energy_power" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Lab Power Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "tasmotalab_energy_power" }
     ]
    }
   ]
  },
  {
   "title": "Switch States",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "LR Vornado",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch.living_room_vornado",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Big Vornado",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch.big_vornado",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Plant Light",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch.plant_light",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Laundry Fan",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch.laundry_fan",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Basement Fan",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch.basement_fan",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Living Room",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "living_room_temperature" }
     ]
    },
    {
     "alias": "Bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "bedroom_temperature" }
     ]
    },
    {
     "alias": "Office",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "home_office_temperature" }
     ]
    },
    {
     "alias": "Outside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weather.my_ecobee",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
     ]
    },
    {
     "alias": "Ecobee",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee_temperature" }
     ]
    },
    {
     "alias": "Basement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "basement_temperature" }
     ]
    },
    {
     "alias": "Garage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "garage_temperature" }
     ]
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "μg/m³",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "vindriktning_d7b6ae_pm_2_5" }
     ]
    }
   ]
  },
  {
   "title": "Sprinklers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "On/Off" }
   ],
   "targets": [
    {
     "alias": "Front Yard",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$SprinklerZones$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "front_yard_rachio" }
     ]
    },
    {
     "alias": "Left Strip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$SprinklerZones$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "left_strip_rachio" }
     ]
    },
    {
     "alias": "Back Near",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$SprinklerZones$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "back_near_rachio" }
     ]
    },
    {
     "alias": "Back Center",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$SprinklerZones$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "back_center_rachio" }
     ]
    },
    {
     "alias": "Back Fence",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$SprinklerZones$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "back_fence_rachio" }
     ]
    },
    {
     "alias": "Right Back",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$SprinklerZones$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "right_back_rachio" }
     ]
    },
    {
     "alias": "Right Strip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$SprinklerZones$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "right_strip_rachio" }
     ]
    }
   ]
  },
  {
   "title": "HVAC",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "alias": "HVAC Fan ON Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate.my_ecobee",
     "select": [
      [
       { "params": [ "fan_str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee" },
      { "condition": "AND", "key": "domain", "operator": "=", "value": "climate" }
     ]
    },
    {
     "alias": "HVAC Heat/Cool",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate.my_ecobee",
     "select": [
      [
       { "params": [ "hvac_action_str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee" },
      { "condition": "AND", "key": "domain", "operator": "=", "value": "climate" }
     ]
    }
   ]
  },
  {
   "title": "Occupancy",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "alias": "Ecobee",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "binary_sensor.my_ecobee_occupancy",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "binary_sensor.bedroom_occupancy",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Office",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "binary_sensor.home_office_occupancy",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Living Room",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "binary_sensor.basement_occupancy",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "Ecobee Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate.my_ecobee",
     "select": [
      [
       { "params": [ "current_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
     ]
    }
   ]
  },
  {
   "title": "Lab Power Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'tasmotalab_energy_power') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "tasmota_energy_power" }
     ]
    },
    {
     "alias": "Amps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "A",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "tasmotalab_energy_current" }
     ]
    }
   ]
  },
  {
   "title": "Aquarium Power Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'tasmota_energy_power') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "tasmotaav_energy_power" }
     ]
    },
    {
     "alias": "Amps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "A",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "tasmotaav_energy_current" }
     ]
    }
   ]
  },
  {
   "title": "Office Power Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'tasmota_energy_power_2') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "tasmotawork_energy_power" }
     ]
    },
    {
     "alias": "Amps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "A",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "tasmotawork_energy_current" }
     ]
    }
   ]
  },
  {
   "title": "ER-X WAN TX/RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "alias": "ER-X RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "MB/s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "erx_wan_rx" }
     ]
    },
    {
     "alias": "ER-X TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "MB/s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "erx_wan_tx" }
     ]
    }
   ]
  },
  {
   "title": "HVAC Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thermostat Target High",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "High Set-Point",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "climate.my_ecobee",
       "select": [
        [
         { "params": [ "target_temp_high" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
       ]
      }
     ]
    },
    {
     "title": "Thermostat Target Low",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Low Set-Point",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "climate.my_ecobee",
       "select": [
        [
         { "params": [ "target_temp_high" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
       ]
      }
     ]
    },
    {
     "title": "Running:",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "Currently Running",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "climate.my_ecobee",
       "select": [
        [
         { "params": [ "equipment_running_str" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
       ]
      }
     ]
    },
    {
     "title": "HVAC Mode",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "HVAC Mode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "climate.my_ecobee",
       "select": [
        [
         { "params": [ "state" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
       ]
      }
     ]
    },
    {
     "title": "Fan Mode",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "Fan Mode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "climate.my_ecobee",
       "select": [
        [
         { "params": [ "fan_mode_str" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
       ]
      }
     ]
    },
    {
     "title": "Climate Mode",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "Climate Mode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "climate.my_ecobee",
       "select": [
        [
         { "params": [ "climate_mode_str" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
       ]
      }
     ]
    },
    {
     "title": "Fan Min. Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "Min. Fan Time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "climate.my_ecobee",
       "select": [
        [
         { "params": [ "fan_min_on_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "my_ecobee" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Switch Status - Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "$switches",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 66 },
     "repeat": "switches",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "/^$switches$/",
       "select": [
        [
         { "params": [ "state" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}