{
 "title": "RT-AC68 Dashboard",
 "tags": [
  "Router",
  "System"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "host",
    "label": "Router:",
    "query": "SHOW TAG VALUES FROM \"snmp.rtn66r\" WITH KEY = \"agent_host\""
   },
   {
    "name": "intf",
    "label": "Interface:",
    "query": "SHOW TAG VALUES FROM \"ifTable\" WITH KEY = \"ifName\" WHERE \"agent_host\" =~ /^$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic In",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ifXTable",
     "query": "SELECT non_negative_derivative(last(\"ifHCInOctets\"), 1s) *8 AS \"In\" FROM \"ifXTable\" WHERE (\"ifName\" = 'eth0') AND $timeFilter GROUP BY time($interval), \"ifName\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.1" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ifXTable",
     "query": "SELECT non_negative_derivative(last(\"ifHCInOctets\"), 1s) *8 AS \"In\" FROM \"ifXTable\" WHERE (\"ifName\" = 'eth0') AND $timeFilter GROUP BY time($interval), \"ifName\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.1" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "snmp.rtn66r",
     "query": "SELECT \"sysUpTime\"  / 100 FROM \"snmp.rtn66r\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_laNames Minute",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "laNames" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laTable",
     "select": [
      [
       { "params": [ "laLoadInt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.1" },
      { "condition": "AND", "key": "laIndex", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "query": "SELECT difference(\"ssCpuRawUser\") / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"User\" FROM \"snmp.rtn66r\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "ssCpuRawIdle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawInterrupt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Interrupt" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawKernel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Kernel" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawNice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Nice" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawSystem" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "System" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawUser" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawWait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "I/O Wait" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawSoftIRQ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Soft IRQ" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawNice\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Nice\" FROM \"snmp.rtn66r\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawSystem\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"System\" FROM \"snmp.rtn66r\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawIdle\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Idle\" FROM \"snmp.rtn66r\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawWait\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"I/O Wait\" FROM \"snmp.rtn66r\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawKernel\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Kernel\" FROM \"snmp.rtn66r\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawInterrupt\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Interrupt\" FROM \"snmp.rtn66r\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawSoftIRQ\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Soft IRQ\" FROM \"snmp.rtn66r\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interrupts / Ctx-Switches (/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.rtn66r",
     "select": [
      [
       { "params": [ "ssRawContexts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Context Switches" ], "type": "alias" }
      ],
      [
       { "params": [ "ssRawInterrupts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Interrupts" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifXTable",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$intf$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifXTable",
     "select": [
      [
       { "params": [ "ifHCInBroadcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Bcast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutBroadcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Bcast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCInMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mcast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mcast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Ucast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Ucast:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.1" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "TCP State Transitions (/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.rtn66r",
     "select": [
      [
       { "params": [ "tcpActiveOpens" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "ActiveOpen" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpPassiveOpens" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "PassiveOpen" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpAttemptFails" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Fail" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpEstabResets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Reset" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.rtn66r",
     "select": [
      [
       { "params": [ "tcpCurrEstab" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Connections" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.rtn66r",
     "select": [
      [
       { "params": [ "memBuffer" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Buffer" ], "type": "alias" }
      ],
      [
       { "params": [ "memCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cache" ], "type": "alias" }
      ],
      [
       { "params": [ "memShared" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Shared" ], "type": "alias" }
      ],
      [
       { "params": [ "memTotalFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.1" }
     ]
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.rtn66r",
     "select": [
      [
       { "params": [ "memAvailReal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Real" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_hrStorageDescr",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hrStorageTable",
     "query": "SELECT (last(\"hrStorageUsed\")/last(\"hrStorageSize\"))  FROM \"hrStorageTable\"  WHERE \"agent_host\" =~ /^$host$/ AND \"hrStorageType\" = '.1.3.6.1.2.1.25.2.1.2' AND $timeFilter GROUP BY time($interval), \"hrStorageDescr\" fill(null)",
     "select": [
      [
       { "params": [ "hrStorageUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "ICMP Summary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "IPv4:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "icmpStatsTable",
     "select": [
      [
       { "params": [ "icmpStatsInMsgs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Msg:In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsOutMsgs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Msg:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "IPv6:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "icmpStatsTable",
     "select": [
      [
       { "params": [ "icmpStatsInMsgs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Msg:In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsOutMsgs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Msg:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "ICMP Message Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_index:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "icmpMsgStatsTable",
     "select": [
      [
       { "params": [ "icmpMsgStatsInPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpMsgStatsOutPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SNMP Messages (/min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.rtn66r",
     "select": [
      [
       { "params": [ "snmpInPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Msgs:In" ], "type": "alias" }
      ],
      [
       { "params": [ "snmpOutPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Msgs:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "snmpInGetResponses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "GetResp:In" ], "type": "alias" }
      ],
      [
       { "params": [ "snmpOutGetResponses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "GetResp:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.1" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"allReqIn\"), 1m) AS \"GetReq:In\", non_negative_derivative(mean(\"allReqOut\"), 1m) AS \"GetReq:Out\" FROM ( SELECT \"snmpInGetRequests\"+\"snmpInGetNexts\" AS \"allReqIn\", \"snmpOutGetRequests\"+\"snmpOutGetNexts\" AS \"allReqOut\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter) WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNMP Objects Retrieved (/min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.rtn66r",
     "select": [
      [
       { "params": [ "snmpInTotalReqVars" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Objects" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.1" }
     ]
    }
   ]
  }
 ]
}